name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android,armv7-linux-androideabi

    - name: Install Rust Android targets
      run: |
        rustup target add aarch64-linux-android
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Android NDK
      run: |
        sdkmanager "ndk;26.1.10909125"
        echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk/26.1.10909125" >> $GITHUB_ENV

    - name: Install frontend dependencies
      run: npm install

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@next

    - name: Create Android project
      run: |
        npm run tauri android init || echo "Android already initialized"

    - name: Build Android APK
      run: npm run tauri android build
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        ANDROID_NDK_HOME: ${{ env.NDK_HOME }}

    - name: List build artifacts
      run: |
        echo "Looking for APK files..."
        find . -name "*.apk" -type f

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          src-tauri/gen/android/app/build/outputs/apk/**/*.apk
        if-no-files-found: warn
        retention-days: 30

    - name: Upload Debug APK (alternative path)
      uses: actions/upload-artifact@v4
      with:
        name: android-debug-apk
        path: |
          src-tauri/gen/android/app/build/outputs/apk/universal/debug/*.apk
        if-no-files-found: ignore
        retention-days: 30

    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.0-${{ github.run_number }}
        name: Release v1.0.0-${{ github.run_number }}
        draft: false
        prerelease: true
        files: |
          src-tauri/gen/android/app/build/outputs/apk/**/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

